In [30]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
df = pd.read_excel("/content/upload_colab.xlsx")
df

                Category1                               Place
0                 History                       Pantai Marina
1                 History               Kampoeng Kopi Banaran
2                Culinary                 Taman Pelangi Jogja
3      Tourist Attraction  Alun-alun Utara Keraton Yogyakarta
4                 Culture                       Pantai Sundak
...                   ...                                 ...
19995            Culinary          Puncak Kebun Buah Mangunan
19996  Tourist Attraction                        Watu Lumbung
19997             History                 Watu Mabur Mangunan
19998             Culture                    Hutan Pinus Asri
19999  Tourist Attraction                  Bukit Lintang Sewu

[20000 rows x 2 columns]

In [32]:
tf = TfidfVectorizer()

tf.fit(df['Category1'])

tf.get_feature_names_out()

array(['attraction', 'culinary', 'culture', 'history', 'nature',
       'tourist'], dtype=object)

In [33]:
tfidf_matrix = tf.fit_transform(df['Category1'])
tfidf_matrix.shape

(20000, 6)

In [34]:
tfidf_matrix.todense()

matrix([[0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        ],
        [0.        , 0.        , 1.        , 0.        , 0.        ,
         0.        ],
        [0.70710678, 0.        , 0.        , 0.        , 0.        ,
         0.70710678]])

In [35]:
pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tf.get_feature_names_out(),
    index=df.Place
).sample(10, axis=0)

,attraction,culinary,culture,history,nature,tourist
Place,,,,,,
Semarang Contemporary Art Gallery,0.000000,0.0,0.0,1.0,0.0,0.000000
Bunker Kaliadem Merapi,0.000000,0.0,1.0,0.0,0.0,0.000000
Taman Tabanas,0.000000,0.0,0.0,0.0,1.0,0.000000
Pantai Marina,0.000000,0.0,1.0,0.0,0.0,0.000000
Taman Pandanaran,0.000000,0.0,0.0,1.0,0.0,0.000000
Lawang Sewu,0.000000,0.0,0.0,0.0,1.0,0.000000
Masjid Kapal Semarang,0.000000,1.0,0.0,0.0,0.0,0.000000
Kampoeng Kopi Banaran,0.000000,0.0,1.0,0.0,0.0,0.000000
Semarang Contemporary Art Gallery,0.000000,0.0,1.0,0.0,0.0,0.000000
Pantai Baruna,0.707107,0.0,0.0,0.0,0.0,0.707107

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

array([[1., 1., 0., ..., 1., 0., 0.],
       [1., 1., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [52]:
cosine_sim_df = pd.DataFrame(
    cosine_sim, index=df.Place, columns=df.Place)

cosine_sim_df

Place,Pantai Marina,Kampoeng Kopi Banaran,Taman Pelangi Jogja,Alun-alun Utara Keraton Yogyakarta,Pantai Sundak,Benteng Pendem,Hutan Wisata Tinjomoyo Semarang,Galaxy Waterpark Jogja,Tebing Breksi,Candi Gedong Songo,...,Pasar Kebon Empring Bintaran,De Mata Museum Jogja,Bunker Kaliadem Merapi,Museum Kereta Ambarawa,Flower Farm Setiya Aji,Puncak Kebun Buah Mangunan,Watu Lumbung,Watu Mabur Mangunan,Hutan Pinus Asri,Bukit Lintang Sewu
Place,,,,,,,,,,,,,,,,,,,,,
Pantai Marina,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Kampoeng Kopi Banaran,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Taman Pelangi Jogja,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Alun-alun Utara Keraton Yogyakarta,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
Pantai Sundak,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Puncak Kebun Buah Mangunan,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Watu Lumbung,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
Watu Mabur Mangunan,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Hutan Pinus Asri,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Bukit Lintang Sewu,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0

In [ ]:
cosine_sim_df.to_csv()

In [55]:
transpose_df = cosine_sim_df.loc["Taman Srigunting"].head(1).T
transpose_df[transpose_df["Taman Srigunting"] == 1].head(5)

Place                         Taman Srigunting
Place
Taman Pelangi Jogja                        1.0
Tebing Breksi                              1.0
Candi Ijo                                  1.0
Sindu Kusuma Edupark (SKE)                 1.0
Kauman Pakualaman Yogyakarta               1.0